export * as Collection from "@effect/html/data/Collection"
export * as Component from "@effect/html/data/Component"
export * as Hole from "@effect/html/data/Hole"
export * as Many from "@effect/html/data/Many"
export * as Placeholder from "@effect/html/data/Placeholder"
export * as Template from "@effect/html/data/Template"
export * as Wire from "@effect/html/data/Wire"
export * as ComponentCache from "@effect/html/io/ComponentCache"
export * as Hooks from "@effect/html/io/Hooks"
export * as TemplateCache from "@effect/html/io/TemplateCache"
export * as WeakCache from "@effect/html/io/WeakCache"

export * from "@effect/html/io/Render"
