export * as component from "@effect/html/data/Component"
export * as hole from "@effect/html/data/Hole"
export * as wire from "@effect/html/data/Wire"
export * as componentCache from "@effect/html/io/ComponentCache"
export * as templateCache from "@effect/html/io/TemplateCache"
export * as weakCache from "@effect/html/io/WeakCache"
